name: CRM Drafting Unrelease Please

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  crm-unrelease-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        name: Release Please
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # optional. customize path to release-please-config.json
          config-file: unrelease-please-config.json
          # optional. customize path to .release-please-manifest.json
          manifest-file: .release-please-manifest.json
      # - uses: actions/checkout@v4
      #   if: >
      #     ${{ steps.release.outputs.prs_created }} &&
      #     ! ${{ steps.release.outputs.releases_created }} 
      #   with:
      #     ref: ${{ fromJson(steps.release.outputs.pr).headBranchName }}
      # - name: Retagged pkg/cmmon
      #   if: >
      #     ${{ steps.release.outputs.prs_created }} &&
      #     ! ${{ steps.release.outputs.releases_created }} 
      #   run: |
      #     git config user.name github-actions[bot]
      #     git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      #     git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
      #     git commit --allow-empty -m "Release-As: ${{ fromJson(steps.release.outputs.pr).title }}"
      #     git push