name: CRM Drafting Unrelease Please

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  crm-unrelease-please:
    runs-on: ubuntu-latest
    env:
        TRUNK_BRANCH: main
        DRAFT_BRANCH: draft/release

    steps:
      - name: echoer
        run: |
          echo "${{TRUNK_BRANCH}}"
          echo "${{DRAFT_BRANCH}}"
      # - uses: actions/checkout@v4
      #   name: Checkout to unrelease/draft branch
      #   ref: ""
      # - name: rebase from trunk
        
      #   run: |
      #     git config user.name github-actions[bot]
      #     git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      #     git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
      #     git rebase $TRUNK_BRANCH
      #     git push
      # - name: revert manifest version patch
      #   run: |
      #     # Extract major and minor versions from version.json
      #     version=$(jq -r '.["."]' .release-please-manifest.json)
      #     major_minor=$(echo "$version" | cut -d '.' -f 1,2)

      #     # Construct the updated version with patch set to 0
      #     updated_version="${major_minor}.0"

      #     # Update the value in the .release-please-manifest.json file
      #     jq --arg updated_version "$updated_version" '.["."] = $updated_version' .release-please-manifest.json > temp.json && mv temp.json .release-please-manifest.json

      # - uses: google-github-actions/release-please-action@v4
      #   id: release
      #   name: Release Please
      #   with:
      #     # this assumes that you have created a personal access token
      #     # (PAT) and configured it as a GitHub action secret named
      #     # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     # optional. customize path to release-please-config.json
      #     config-file: unrelease-please-config.json
      #     # optional. customize path to .release-please-manifest.json
      #     manifest-file: .release-please-manifest.json
      #     target-branch: ${{ DRAFT_BRANCH }}
